apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheusrules-writer
  namespace: openshift-user-workload-monitoring
rules:
- apiGroups: ["monitoring.coreos.com"]
  resources: ["prometheusrules"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-prometheusrules
  namespace: openshift-user-workload-monitoring
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheusrules-writer
